### ISSUE TITLE
GitBook 本地使用排雷，及导出基本可用的 PDF 版本 - Alpha Hinex's Blog

### ISSUE THREAD

**Issue by AlphaHinex** [AlphaHinex/AlphaHinex.github.io#144]
https://alphahinex.github.io/2022/09/18/gitbook-export-fine-enough-pdf/

**Comment by AlphaHinex** [comment]
Need to use fixed version of cheerio, newer version has no raw string of spec, will cause error below:

```
  info: install plugin "ancre-navigation" (*) from NPM with version 1.0.0
  /root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/aproba/index.js:25
      if (args[ii] == null) throw missingRequiredArg(ii)
                            ^
  
  Error: Missing required argument #1
      at andLogAndFinish (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/kage-metadata.js:31:3)
      at fetchPackageMetadata (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/kage-metadata.js:51:22)
      at resolveWithNewModule (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/install/90:12)
      at /root/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:491:7
      at /root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50
      at /root/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:37:12
      at addRequestedAndFinish (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/kage-metadata.js:67:5)
      at returnAndAddMetadata (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/kage-metadata.js:121:7)
      at pickVersionFromRegistryDocument (/root/.gitbook/versions/3.2.3/node_modules/npm/lib/kage-metadata.js:138:20)
      at /root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50 {
    code: 'EMISSINGARG'
  }
```

```bash
npm install cheerio@0.22.0
```
