### ISSUE TITLE
识别旋转验证码图片角度 - Alpha Hinex's Blog

### ISSUE THREAD

**Issue by AlphaHinex** [AlphaHinex/AlphaHinex.github.io#226]
https://alphahinex.github.io/2024/05/12/rotate-captcha/

**Comment by 838514984** [comment]
你好，按照文章介绍，顺序安装下来，最后没有models和datasets文件夹，这个是啥问题额，只有model，和dataset文件夹

**Comment by AlphaHinex** [comment]
> @838514984
> 你好，按照文章介绍，顺序安装下来，最后没有models和datasets文件夹，这个是啥问题额，只有model，和dataset文件夹

https://www.jianshu.com/p/09bd748b8a8e 😜

**Comment by 838514984** [comment]
再问下大佬，这个可以训练么，我把图片放在一个文件夹，然后路径也指定了这个文件夹，里面的图片是jpg格式，但是运行train_RotNetR.py的时候报错了，可以请教一下怎么解决吗，感谢。
train_RotNetR.py中dataset_root已修改
#################################
### Custom configuration area ###
dataset_root = Path("C:/Users/admin/rotate-captcha-crack/trainimg/")

提示：
(rotate) C:\Users\admin\rotate-captcha-crack>python train_RotNetR.py
Traceback (most recent call last):
  File "C:\Users\admin\rotate-captcha-crack\train_RotNetR.py", line 30, in <module>
    img_paths = google_street_view.get_paths(dataset_root)
  File "C:\Users\admin\rotate-captcha-crack\rotate_captcha_crack\dataset\paths\google_street_view\iterator.py", line 24, in get_paths
    sequence = SequenceRoot(list(iterator))
  File "C:\Users\admin\rotate-captcha-crack\rotate_captcha_crack\dataset\pipeline.py", line 84, in __next__
    item = fn(item)
  File "C:\Users\admin\rotate-captcha-crack\rotate_captcha_crack\dataset\paths\google_street_view\filter.py", line 19, in filter
    viewid = int(segs[1])
IndexError: list index out of range
